language: scala

scala:
  - 2.12.3

jdk:
  - openjdk8

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete
  - find $HOME/.cache/coursier -name "*.lock"     -print -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.cache/coursier

script: sbt clean +test
